---
- name: IPTables | remove ufw packages
  package:
    name: ufw
    state: absent
  register: ufw_uninstall
  retries: 5
  until: ufw_uninstall is success
  tags: install

- name: IPTables | remove ufw configuration
  file:
    path: /etc/ufw
    state: absent
  tags: install

- name: IPTables | install packages
  package:
    name:
      - iptables
      - iptables-persistent
    state: present
  register: iptables_install
  retries: 5
  until: iptables_install is success
  tags: install

- name: IPTables | create validate scripts
  copy:
    src: "iptables-validate"
    dest: "/usr/local/bin/iptables-validate"
    mode: 0755
  tags: install

- name: IPTables | create iptables config directory
  file:
    path: "{{ directory_item }}"
    state: directory
    mode: 0755
  loop:
    - "/etc/network/if-up.d"
    - "/etc/iptables/"
  loop_control:
    loop_var: directory_item

- name: IPTables | set iptables.v4 template
  template:
    src: rules.v4.j2
    dest: /etc/iptables/rules.v4
    validate: /usr/local/bin/iptables-validate %s
    mode: 0644
    backup: yes
  tags: config
  notify:
    - reload ip4tables

# - name: IPTables | set iptables.v6 template
#   template:
#     src: rules.v6.j2
#     dest: /etc/iptables/rules.v6
#     mode: 0644
#     backup: yes
#     validate: /usr/local/bin/iptables-validate %s
#   tags: config
#   notify:
#     - reload ip6tables

- name: IPTables | create iptables up script for network interface(s)
  copy:
    src: iptables
    dest: /etc/network/if-up.d/iptables
    mode: 0755
...