---
- name: Merge configurations
  set_fact:
    fw_config:
      "{{
        firewall_defaults|default({}) | combine(
          firewall,
          firewall1|default({}),
          firewall2|default({}),
          firewall3|default({}),
          firewall4|default({}),
          recursive=True,
          list_merge='append'
        )
      }}"
  tags: always

- name: Show merged configuration
  debug:
    msg: "{{ fw_config }}"
  when: ipset_rules is defined
  tags: always

- name: Get ipset files
  set_fact:
    ipset_rules_files: "{{ ipset_rules_files | default([]) +
          [
            {
              'name': item.name,
              'type': item.type,
              'state': item.state,
              'addresses': lookup('ansible.builtin.file', item.file).splitlines()
            }
          ]
        }}"
  when: ipset_files is defined
  loop: '{{ ipset_files }}'
  tags: ipset

- name: Merge ipset configurations
  set_fact:
    ipset_rules_merged:
      "{{ list1 | community.general.lists_mergeby(
                    ipset_rules_files|default([]),
                    ipset_rules,
                    ipset_rules1|default([]),
                    ipset_rules2|default([]),
                    'name',
                    recursive=True,
                    list_merge='append'
                 ) }}"
  when: ipset_rules is defined
  tags: ipset

- name: show merged ipset rules
  debug:
    msg: "{{ ipset_rules_merged }}"
  tags: ipset

- name: ipset | setup ipset if defined
  include_tasks:
    file: ipset.yml
    apply:
      tags:
        - ipset
        - firewall
  when: ipset_rules is defined
  tags: always

- name: UFW | setup ufw if defined
  include_tasks:
    file: ufw.yml
    apply:
      tags:
        - ufw
        - firewall
  when: firewall_ufw
  tags: always

- name: IPTables | setup IPtables by default
  include_tasks:
    file: iptables.yml
    apply:
      tags:
        - iptables
        - firewall
  when:
    - not firewall_ufw
    - ansible_facts['os_family'] == "Debian" # Debian 10,9,..,Ubuntu 20.04,18.04,e.t.c
  tags: always

- name: IPTables | setup IPtables by default
  include_tasks:
    file: iptables_rh.yml
    apply:
      tags:
        - iptables
        - firewall
  when:
    - not firewall_ufw
    - ansible_facts['os_family'] == "RedHat" # CentOS 8, CentOS 7,Fedora 33, Amazon Linux 2, e.t.c
  tags: always

- name: sysctl
  include_tasks:
    file: sysctl.yml
    apply:
      tags:
        - sysctl
        - firewall
  tags: always
...