---
- name: set default interfaces
  ansible.builtin.set_fact:
    interfaces:
      - "all"
      - "default"
      - "lo"
  tags:
    - ipv6

- name: gather instance interfaces
  ansible.builtin.set_fact:
    interfaces: "{{ interfaces + [ item ] }}"
  with_items:
    "{{ ansible_interfaces }}"
  when:
    - item is match("eth*") or item is match("ens*")
  tags:
    - ipv6

- name: show interfaces
  ansible.builtin.debug:
    var: interfaces
  tags:
    - ipv6

- name: disable IPv6
  sysctl:
    name=net.ipv6.conf.{{ item }}.disable_ipv6
    value=1
    state=present
    sysctl_file=/etc/sysctl.conf
    reload=yes
  with_items: "{{ interfaces }}"
  when: not firewall_enable_ipv6
  tags:
    - ipv6

- name: enable IPv6
  sysctl:
    name=net.ipv6.conf.{{ item }}.disable_ipv6
    value=0
    state=present
    sysctl_file=/etc/sysctl.conf
    reload=yes
  with_items: "{{ interfaces }}"
  when: firewall_enable_ipv6
  tags:
    - ipv6

- name: enable ip forwarding
  sysctl:
    name=net.ipv4.ip_forward
    value=1
    state=present
    sysctl_file=/etc/sysctl.conf
    reload=yes
  when: (firewall_nat is defined and firewall_nat.snat_enabled) or (fw_config.dockerhost is defined and fw_config.dockerhost)

- name: disable ip forwarding
  sysctl:
    name=net.ipv4.ip_forward
    value=0
    state=present
    sysctl_file=/etc/sysctl.conf
    reload=yes
  when:
   - firewall_nat is not defined or (firewall_nat is defined and not firewall_nat.snat_enabled)
   - fw_config.dockerhost is not defined or (fw_config.dockerhost is defined and not fw_config.dockerhost)
...