---
- name: disable IPv6
  sysctl:
    name={{ item }}
    value=1
    state=present
    sysctl_file=/etc/sysctl.conf
    reload=yes
  with_items:
    - "net.ipv6.conf.all.disable_ipv6"
    - "net.ipv6.conf.default.disable_ipv6"
    - "net.ipv6.conf.lo.disable_ipv6"
  when: not firewall_enable_ipv6
  tags:
    - ipv6

- name: enable IPv6
  sysctl:
    name={{ item }}
    value=0
    state=present
    sysctl_file=/etc/sysctl.conf
    reload=yes
  with_items:
    - "net.ipv6.conf.all.disable_ipv6"
    - "net.ipv6.conf.default.disable_ipv6"
    - "net.ipv6.conf.lo.disable_ipv6"
  when: firewall_enable_ipv6
  tags:
    - ipv6

- name: enable ip forwarding
  sysctl:
    name=net.ipv4.ip_forward
    value=1
    state=present
    sysctl_file=/etc/sysctl.conf
    reload=yes
  when: firewall_nat is defined and firewall_nat.snat_enabled

- name: disable ip forwarding
  sysctl:
    name=net.ipv4.ip_forward
    value=0
    state=present
    sysctl_file=/etc/sysctl.conf
    reload=yes
  when: firewall_nat is not defined or (firewall_nat is defined and not firewall_nat.snat_enabled)
...