---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint -c .yamllint .
  ansible-lint -c .ansible-lint . -v
platforms:
  - name: instance
    image: ubuntu:20.04
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    tty: True
    env:
      container: docker
provisioner:
  name: ansible
verifier:
  name: ansible
...